accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns =[
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
]

reddimental/urls.py
from django.urls import path
from reddimental import views
from django.conf.urls import url, include
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('analyze_sentiment/', views.analyze_sentiment, name="analyze_sentiment"),
    path('accounts/', include('accounts.urls'))
]

reddit_sentiment_dashboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reddimental.urls'))
]

accounts/models.py
from django.db import models

# Create your models here.

reddimental/models.py
import uuid
from datetime import datetime

from django.db import models
from django.utils import timezone
import pytz


# Create your models here.

class Submission(models.Model):
    submission_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    timestamp = models.DateTimeField(default=timezone.now)
    author = models.TextField(default='', null=True)
    title = models.TextField(default='', null=True)


class Comment(models.Model):
    comment_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    timestamp = models.DateTimeField(default=timezone.now)
    author = models.TextField(default='', null=True)
    comment_text = models.TextField(default='', null=True)
    submission = models.ForeignKey(Submission, on_delete=models.CASCADE)

reddimental/forms.py
from django import forms


class SubredditForm(forms.Form):
    subreddit = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'uk-input uk-width-auto', 'placeholder': 'e.g. politics'}), label='r/')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            # log the user in
            return redirect('index')
    else:
        form = UserCreationForm()
    form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log in the user
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('index')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('index')

reddimental/views.py
from datetime import datetime

from django.shortcuts import render
from .forms import SubredditForm
from .models import Submission, Comment
from .praw_reddit_scraper import RedditScrapeManager
from django.contrib.auth.decorators import login_required
import pandas as pd
import numpy as np

import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer as SIA


# Create your views here.
def index(request):
    subreddit_form = SubredditForm()
    return render(request, 'index.html', {'subreddit_form': subreddit_form})


def about(request):
    return render(request, 'about.html')


@login_required(login_url="/accounts/login/")
def analyze_sentiment(request):
    subreddit = request.GET.get('subreddit')
    # Initialize instance of RedditScrapeManager, to call methods on
    scrape_instance = RedditScrapeManager(subreddit)
    # Get subreddit title, subscriber count, and description for banner
    subreddit_info = scrape_instance.get_subreddit_info()
    # Get all submission/comment info
    master_submission_data_list = scrape_instance.get_submission_data()
    # Calculate total average sentiment score from all submissions, and append to subreddit_info dictionary
    subreddit_total_sentiment_score = 0
    subreddit_total_num_comments = 0
    for submission in master_submission_data_list:
        subreddit_total_num_comments += len(submission['comments'])
        subreddit_total_sentiment_score += submission['average_sentiment_score'] * (len(submission['comments']))

    subreddit_average_sentiment_score = subreddit_total_sentiment_score / subreddit_total_num_comments
    subreddit_info['average_sentiment_score'] = round(subreddit_average_sentiment_score, 1)

    sia = SIA()
    qs1 = Submission.objects.filter(title__icontains=subreddit).distinct()
    x = [x.title for x in qs1]
    y = [sia.polarity_scores(y.title)['compound'] * 100 for y in qs1]
    chart1 = RedditScrapeManager.get_plot1(x, y)

    qs2 = Comment.objects.filter(comment_text__icontains=subreddit).distinct()
    x = [x.comment_text for x in qs2]
    y = [sia.polarity_scores(y.comment_text)['compound'] * 100 for y in qs2]
    chart2 = RedditScrapeManager.get_plot2(x, y)

    qs3 = Comment.objects.filter(comment_text__icontains=subreddit).distinct()
    results = []
    results = [sia.polarity_scores(x.comment_text) for x in qs3]
    df = pd.DataFrame.from_records(results)
    print(df)
    df['label'] = 0
    df.loc[df['compound'] > 0.1, 'label'] = 1
    df.loc[df['compound'] < -0.1, 'label'] = -1
    counts = df.label.value_counts(normalize=True) * 100
    print(counts)
    x = counts.index
    y = counts
    chart3 = RedditScrapeManager.get_plot3(x, y)
    qs4 = Submission.objects.filter(title__icontains=subreddit).distinct()
    results = []
    for x in qs4:
        scores = sia.polarity_scores(x.title)
        scores['timestamp'] = x.timestamp
        results.append(scores)
    df = pd.DataFrame.from_records(results)
    df.loc[df['compound'] > 0.1, 'label'] = 1
    df.loc[df['compound'] < -0.1, 'label'] = -1
    x1 = df[df['label'] == -1].timestamp
    x2 = df[df['label'] == 1].timestamp
    y1 = df[df['label'] == -1].compound * 100
    y2 = df[df['label'] == 1].compound * 100
    chart4 = RedditScrapeManager.get_plot4(x1, y1, x2, y2)

    if scrape_instance.sub_exists():
        args = {'subreddit': subreddit, 'subreddit_info': subreddit_info,
                'master_submission_data_list': master_submission_data_list, 'chart1': chart1, 'chart2': chart2,
                'chart3': chart3, 'chart4': chart4}
        return render(request, 'analyze_sentiment.html', args)

    '''
    Form validation logic. WIP.
    else:
        form = SubredditForm()
        return render(request, 'index.html', {'subreddit_form': form})
    '''

accounts/templates/accounts/login.html
{% extends "base.html" %}

{%block content %}
    <h1>Log in</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next}}">
        {% endif %}
        <input type="submit" value="Login">
    </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}

{%block content %}
    <h1>Signup</h1>
    <form class="site-form" action="/accounts/signup/" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

reddimental/templates/about.html
<!doctype html>
{% extends "base.html" %}
{% block content %}
<html>
<head>
    {% load static %}
    <title>Reddit Sentiment</title>
    <link rel="icon" href="img/favicon.ico">
    <style>
        .wrap::before {
            position: absolute;
            height: 100vh;
            width: 100vw;
            content: '';
            z-index: 1;
            background-color: rgba(0,0,0,0.5);
        }
        .lead {
            font-size: 1.175em;
            font-weight: 300;
        }
        .uk-logo img {
            height: 28px;
        }
	</style>

</head>

<body class="uk-light wrap uk-background-norepeat uk-background-cover uk-background-center-center uk-cover-container uk-background-secondary">
    <img data-srcset="https://picsum.photos/id/382/640/700/?blur=8 640w,
                    https://picsum.photos/id/382/960/700/?blur=8 960w,
                    https://picsum.photos/id/382/1200/900/?blur=8 1200w,
                    https://picsum.photos/id/382/2000/1000/?blur=8 2000w"
            sizes="100vw"
            data-src="https://picsum.photos/id/382/1200/900/?blur=8" alt="" data-uk-cover data-uk-img
    >
    <div class="uk-flex uk-flex-center uk-flex-middle uk-height-viewport uk-position-z-index uk-position-relative" data-uk-height-viewport="min-height: 400">
        
        <!-- NAV -->
        <div class="uk-position-top">
            <div class="uk-container uk-container-small">
                <nav class="uk-navbar-container uk-navbar-transparent" data-uk-navbar>  
                    <div class="uk-navbar-left">
                        <div class="uk-navbar-item">
                            <a class="uk-logo" href="/">Reddimental</a>
                        </div>
                    </div>
                    <div class="uk-navbar-right">
                        <ul class="uk-navbar-nav">
                            <li class="uk-active uk-visible@m"><a href="https://github.com/bzgnc/SWE-573" data-uk-icon="icon: github; ratio: 1.3"></a></li>
                            <li class="uk-active uk-visible@m"><a href="/" data-uk-icon="home"></a></li>
                            <li class="uk-visible@s"><a href="">About</a></li>
                            <li class="uk-active uk-visible@s"><form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                                {% csrf_token %}
                                <button type="submit" style="background:none;color:#aaa;cursor:pointer;border:0;margin-top:32px;font-size:93%;font-family:Arial Narrow">LOGOUT</button>
                            </form></li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
        <!-- /NAV -->
        <!-- ABOUT TEXT -->
        <div class="uk-container uk-container-small uk-flex-auto uk-text-left" data-uk-scrollspy="target: > .animate; cls: uk-animation-slide-bottom-small uk-invisible; delay: 300">
            <article class="uk-article animate uk-invisible">
                <h1 class="uk-article-title">About</h1>
            
                <p class="uk-text-lead">The source code for this website can be found on my <a href="https://github.com/bzgnc/SWE-573" uk-icon="icon: github; ratio: 2"></a>.</p>
                <p class="uk-text-meta"><strong>TECHNOLOGIES USED</strong></p>
                
                <dl class="uk-description-list uk-description-list-divider">
                        <dt class="uk-text-primary">Django</dt>
                        <dd>Django, a Python-based web framework, composes the skeleton of the website.</dd>
                        <dt class="uk-text-primary">Reddit API</dt>
                        <dd>Reddit's API is queried with the user's desired subreddit, returning detailed comment and submission information.</dd>
                        <dt class="uk-text-primary">Python NLTK Vader Sentiment Analysis Module</dt>
                        <dd>Python NLTK vader sentiment analysis module is used on cleaned comment text, returning sentiment data to be parsed.</dd>
                </dl>
                <p class="uk-text-small">Note: if all comments show the same number of upvotes, that means the subreddit has set comment scores to be hidden for a period of time after being posted.</p>
            </article>
        </div>
        <!-- / ABOUT TEXT -->
    </div>
</body>
</html>

{% endblock %}

reddimental/templates/analyze_sentiment.html
<!doctype html>
{% extends "base.html" %}
{% block content %}
<html lang="en">
	<head>
		{% load static %}
		<title>Reddimental</title>
		<!-- CSS -->
		<link rel="stylesheet" type="text/css" href="{% static 'analyze_sentiment.css' %}">
	</head>
	<body>
		<!-- TOP -->
		<div class="top-wrap uk-position-relative uk-light uk-background-secondary">
			
		<!-- NAV -->
		<div class="nav" data-uk-sticky="cls-active: uk-background-secondary uk-box-shadow-medium; top: 100vh; animation: uk-animation-slide-top">
			<div class="uk-container">
				<nav class="uk-navbar uk-navbar-container uk-navbar-transparent" data-uk-navbar>
					<div class="uk-navbar-left">
						<div class="uk-navbar-item uk-padding-remove-horizontal">
							<a class="uk-logo" title="Logo" href="/">Reddimental</a>
						</div>
					</div>
					<div class="uk-navbar-right">
						<ul class="uk-navbar-nav uk-visible@s">
							<li class="uk-active uk-visible@m"><a href="https://github.com/bzgnc/SWE-573" data-uk-icon="icon: github; ratio: 1.3"></a></li>
							<li class="uk-active uk-visible@m"><a href="/" data-uk-icon="home"></a></li>
							<li><a href="/about">About</a></li>
							<li class="uk-active uk-visible@s"><form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                                {% csrf_token %}
                                <button type="submit" style="background:none;color:#aaa;cursor:pointer;border:0;margin-top:32px;font-size:93%;font-family:Arial Narrow">LOGOUT</button>
                            </form></li>
						</ul>
					</div>
				</nav>
			</div>
		</div>
		<!-- /NAV -->

		<div class="uk-cover-container uk-light uk-flex uk-flex-middle top-wrap-height">	
			<!-- TOP CONTAINER -->
			<div class="uk-container uk-flex-auto top-container uk-position-relative uk-margin-medium-top" data-uk-parallax="y: 0,50; easing:0; opacity:0.2">
				<div class="uk-width-1-2@s" data-uk-scrollspy="cls: uk-animation-slide-right-medium; target: > *; delay: 150">
					<h6 class="uk-text-primary uk-margin-small-bottom">r/{{subreddit}} - {{subreddit_info.subscribers}} subscribers</h6>
					<h1 class="uk-margin-remove-top">{{subreddit_info.title}}</h1>
					<p class="subtitle-text uk-visible@s"> {{subreddit_info.public_description}} </p>
					<div title="Sentiment Score" class="uk-button uk-button-primary uk-disabled uk-border-pill" data-uk-scrollspy-class="uk-animation-fade">Average Sentiment Score: {{subreddit_info.average_sentiment_score}}</div>
				</div>
			</div>
			<!-- /TOP CONTAINER -->
			<!-- TOP IMAGE -->
			<img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-srcset="https://i.picsum.photos/id/20/700/?image=816 640w,
			https://i.picsum.photos/id/20/960/700/ 960w,
			https://i.picsum.photos/id/20/1200/900/ 1200w,
			https://i.picsum.photos/id/20/2000/1000/ 2000w"
			data-sizes="100vw"
			data-src="https://picsum.photos/id/1045/1200/900/" alt="" data-uk-cover data-uk-img data-uk-parallax="opacity: 1,0.1; easing:0"
			>
		</div>
			<!-- /TOP IMAGE -->
			<!-- NAV ARROW DOWN -->
			<div class="uk-position-bottom-center uk-position-medium uk-position-z-index uk-text-center">
				<a href="#submission" data-uk-scroll="duration: 500" data-uk-icon="icon: arrow-down; ratio: 2"></a>
			</div>
			<!-- /NAV ARROW DOWN -->
		</div>
		<!-- /TOP -->
		{% if chart1 %}
			<img src="data:image/png;base64, {{chart1|safe}}">
		{% endif %}
		{% if chart2 %}
			<img src="data:image/png;base64, {{chart2|safe}}">
		{% endif %}
		{% if chart3 %}
			<img src="data:image/png;base64, {{chart3|safe}}">
		{% endif %}
		{% if chart4 %}
			<img src="data:image/png;base64, {{chart4|safe}}">
		{% endif %}
		<!-- SUBMISSION -->
		{% for submission in master_submission_data_list %}
		<section id = "submission" class="uk-section uk-section-secondary uk-section-large">
			<div class="uk-container">
				<div class="uk-grid uk-child-width-3-5@l uk-flex-left">
					<div>
						<h6>{{submission.score}} upvotes ({{submission.upvote_ratio}}% upvote ratio)</h6>
						<h2 class="uk-margin-small-top uk-h1"><a href={{submission.url}}>{{submission.title}}</a></h2>
						<p class="subtitle-text">
							Posted by u/{{submission.author}} at {{submission.timestamp}}
						</p>
						<div title="Sentiment Score" class="uk-button uk-button-primary uk-disabled uk-border-pill" data-uk-scrollspy-class="uk-animation-fade">Average Sentiment Score: {{submission.average_sentiment_score}}</div>
					</div>
				</div>
			</div>
		</section>
		<!-- COMMENTS SECTION -->
		<section class="uk-cover-container overlay-wrap">
			<img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-srcset="https://picsum.photos/640/650/?image=770 640w,
			https://picsum.photos/id/171/960/650/?blur 960w,
			https://picsum.photos/id/171/1200/650/?blur 1200w,
			https://picsum.photos/id/171/2000/650/?blur 2000w"
			data-sizes="100vw"
			data-src="https://picsum.photos/id/171/1200/650/?blur" alt="" data-uk-cover data-uk-img
			>
			<div class="uk-container uk-position-z-index uk-position-relative uk-section uk-section-xlarge uk-light">
				<div class="uk-grid uk-flex-left">
					
					<div class="uk-width-5-5@m uk-padding-remove" data-uk-parallax="y: 50,-50; easing: 0; media:@l">
						<h5>COMMENTS</h5>
						<div class="uk-position-relative uk-visible-toggle uk-light" data-uk-slider="easing: cubic-bezier(.16,.75,.47,1)">
							<ul class="uk-slider-items uk-child-width-1-1">
								{% for comment in submission.comments %}
								<li>
									<div data-uk-slider-parallax="opacity: 0.2,1,0.2">
										<h3 class="">{{comment.text}}</h3>
										<h6>{{submission.score}} upvotes</h6>
										<p class="uk-text-meta">Posted by u/{{comment.author}} at {{comment.timestamp}}</p>
										<div title="Sentiment Score" class="uk-button uk-button-primary uk-disabled uk-border-pill" data-uk-scrollspy-class="uk-animation-fade">Sentiment Score: {{comment.sentiment_score}}</div>
									</div>
								</li>
								{% endfor %}
							</ul>
							<ul class="uk-slider-nav uk-dotnav uk-margin-top"><li></li></ul>
						</div>
					</div>
					
				</div>
			</div>
		</section>
		<!-- COMMENTS SECTION -->
		{% endfor %}
		<!-- /SUBMISSION -->


		
		<!-- JS FILES -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.1.5/js/uikit.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.1.5/js/uikit-icons.min.js"></script>
	</body>
</html>
{% endblock %}

reddimental/templates/analyze_sentiment_temp.html
<!doctype html>
{% extends "base.html" %}
{% block content %}
<html>
<head>
    {% load static %}
    <title>Reddit Sentiment</title>
    <link rel="icon" href="img/favicon.ico">
    <style>
        .wrap::before {
            position: absolute;
            height: 20vh;
            width: 100vw;
            content: '';
            z-index: 1;
            background-color: rgba(0,0,0,0.5);
        }
        .lead {
            font-size: 1.175em;
            font-weight: 300;
        }
        .uk-logo img {
            height: 32px;
        }
    </style>
</head>

<body class="uk-light wrap uk-background-cover uk-background-center-center uk-cover-container uk-background-secondary">
    <img data-srcset="https://picsum.photos/id/382/640/700/?blur=8 640w,
                    https://picsum.photos/id/382/960/700/?blur=8 960w,
                    https://picsum.photos/id/382/1200/900/?blur=8 1200w,
                    https://picsum.photos/id/382/2000/1000/?blur=8 2000w"
            sizes="100vw"
            data-src="https://picsum.photos/id/382/1200/900/?blur=8" alt="" data-uk-cover data-uk-img
    >
    <div class="uk-flex uk-flex-center uk-flex-middle uk-position-z-index uk-position-relative" data-uk-height-viewport="min-height: 400">
        
        <!-- NAV -->
        <div class="uk-position-top">
            <div class="uk-container uk-container-small">
                <nav class="uk-navbar-container uk-navbar-transparent" data-uk-navbar>  
                    <div class="uk-navbar-left">
                        <div class="uk-navbar-item">
                            <a class="uk-logo" href="/">Reddimental</a>
                        </div>
                    </div>
                    <div class="uk-navbar-right">
                        <ul class="uk-navbar-nav">
                            <li class="uk-active uk-visible@m"><a href="/" data-uk-icon="home"></a></li>
                            <li class="uk-visible@s"><a href="/about">About</a></li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
        <!-- /NAV -->
        <!-- SUBMISSION -->
        <div class="uk-container uk-container-medium uk-flex-auto uk-text-left" data-uk-scrollspy="target: > .animate; cls: uk-animation-slide-bottom-small uk-invisible; delay: 300">
            <article class="uk-article animate uk-invisible">
                <h1 class="uk-article-title">Title Here</h1>
            
                <p class="uk-text-lead">The source code for this website can be found on my <a href="https://github.com/bzgnc/SWE-573" uk-icon="icon: github; ratio: 2"></a>.</p>
            
                <p class="uk-text-meta"><strong>TECHNOLOGIES USED</strong></p>
                {% for x in test_list %}
                    <!-- COMMENT -->
                    <header class="uk-comment-header uk-grid-medium uk-flex-middle" uk-grid>
                        <div class="uk-width-expand">
                            <h4 class="uk-comment-title uk-margin-remove"><a class="uk-link-reset" href="#">Author</a></h4>
                            <ul class="uk-comment-meta uk-subnav uk-subnav-divider uk-margin-remove-top">
                                <li><a href="#">12 days ago</a></li>
                                <li><a href="#">Sentiment Score {{x}}</a></li>
                            </ul>
                        </div>
                    </header>
                    <div class="uk-comment-body">
                        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
                    </div>
                    <!-- / COMMENT -->
                    <hr class="uk-divider-icon">
                {% endfor %}
                </article>
        </div>
        <!-- / SUBMISSION -->
    </div>
</body>
</html>
{% endblock %}

reddimental/templates/index.html
<!doctype html>
{% extends "base.html" %}
{% block content %}
<html>
<head>
    {% load static %}
    <title>Reddit Sentiment</title>
    <link rel="icon" href="img/favicon.ico">
    <style>
        .wrap::before {
            position: absolute;
            height: 100vh;
            width: 100vw;
            content: '';
            z-index: 1;
            background-color: rgba(0,0,0,0.5);
        }
        .lead {
            font-size: 1.175em;
            font-weight: 300;
        }
        .uk-logo img {
            height: 28px;
        }
	</style>

</head>

<body class="uk-light wrap uk-background-norepeat uk-background-cover uk-background-center-center uk-cover-container uk-background-secondary">
    <img data-srcset="https://picsum.photos/id/20/3670/2462/?blur=8 640w,
                    https://picsum.photos/id/20/3670/2462/?blur=8 960w,
                    https://picsum.photos/id/20/3670/2462/?blur=8 1200w,
                    https://picsum.photos/id/20/3670/2462/?blur=8 2000w"
            sizes="100vw"
            data-src="https://picsum.photos/id/274/1200/900/?blur=8" alt="" data-uk-cover data-uk-img
    >
    <div class="uk-flex uk-flex-center uk-flex-middle uk-height-viewport uk-position-z-index uk-position-relative" data-uk-height-viewport="min-height: 400">
        <!-- NAV -->
        <div class="uk-position-top">
            <div class="uk-container uk-container-small">
                <nav class="uk-navbar-container uk-navbar-transparent" data-uk-navbar>  
                    <div class="uk-navbar-left">
                        <div class="uk-navbar-item">
                            <a class="uk-logo" href="">Reddimental</a>
                        </div>
                    </div>
                    <div class="uk-navbar-right">
                        <ul class="uk-navbar-nav">
                            <li class="uk-active uk-visible@m"><a href="https://github.com/bzgnc/SWE-573" data-uk-icon="icon: github; ratio: 1.3"></a></li>
                            <li class="uk-active uk-visible@m"><a href="" data-uk-icon="home"></a></li>
                            <li class="uk-visible@s"><a href="/about/">About</a></li>
                            <li class="uk-active uk-visible@s"><form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                                {% csrf_token %}
                                <button type="submit" style="background:none;color:#aaa;cursor:pointer;border:0;margin-top:32px;font-size:93%;font-family:Arial Narrow">LOGOUT</button>
                            </form></li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
        <!-- /NAV -->
        <!-- TEXT -->
        <div class="uk-container uk-container-small uk-flex-auto uk-text-center" data-uk-scrollspy="target: > .animate; cls: uk-animation-slide-bottom-small uk-invisible; delay: 300">
            <h1 class="uk-heading-primary animate uk-invisible" style="font-weight: 500;">Reddit Sentiment Analyzer</h1>
            <div class="uk-width-4-5@m uk-margin-auto animate uk-invisible">
                <p class="lead uk-text-secondary">Enter a subreddit, and view the top sentiments Redditors express and share:</p>
            </div>

            <!-- SUBREDDIT FORM -->
            <form class="uk-margin-medium-top animate uk-invisible" data-uk-margin data-uk-scrollspy-class="uk-animation-fade uk-invisible" method="GET" action="/analyze_sentiment/">                
                <div class="uk-margin">
                    {{subreddit_form.as_p}}
                </div>
                <button type="submit" class="uk-button uk-button-default uk-button-large uk-width-2-3 uk-width-auto@s" data-uk-icon="arrow-right">Analyze</button>
            </form>
            <!-- SUBREDDIT FORM -->
        </div>
        <!-- /TEXT -->
    </div>
</body>
</html>

{% endblock %}

reddit_sentiment_dashboard/templates/base.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- UIkit CSS -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.1.6/css/uikit.min.css" />
</head>

<body>
    {% block content %}{% endblock %}
    <div class="uk-flex uk-flex-center uk-flex-middle uk-position-z-index uk-position-relative">
        <!-- FOOT -->
        <div class="uk-position-bottom-center uk-position-small">
            <span class="uk-text-small uk-text-center">Ulas Can Inan © 2020 | Powered by <img src="{% static 'reddit-logo.svg'%}" width="30" height="30" uk-svg> API</span>
        </div>
        <!-- /FOOT -->
    </div>
        <header class="wrapper">
        <h1><a href="{% url 'index' %}" alt="SWE-573"></a></h1>
        <nav>
            <ul>
                <li>
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                    </form>
                </li>
            </ul>
        </nav>
    </header>
</body>

<!-- UIkit JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.1.6/js/uikit.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.1.6/js/uikit-icons.min.js"></script>
</html>